### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading '0')

### ISSUE THREAD

**Issue by dingzhenbaohujiaran** [70loKirin/ATRI-plugin#1]
![日志](https://user-images.githubusercontent.com/105736187/187035965-c247cc2d-df0a-4ed4-b787-ad7c988a9791.png)
显示无法读取未定义的属性，请问该如何解决呢

**Comment by qllokirin** [comment]
请问你的百度翻译api配置好了吗，需要把appid和key填入`Yunzai-Bot\plugins\ATRI-plugin\apps\atri.js`的50和51行
（还没研究yaml文件在js里面的用法   所以直接填到源代码  我是懒狗）
正常输出应该会在控制台里输出一次日语，像这样
![image](https://user-images.githubusercontent.com/91271243/187036380-fa56e8a6-8858-4692-ad68-4d194d3e54bf.png)

**Comment by dingzhenbaohujiaran** [comment]
> 请问你的百度翻译api配置好了吗，需要把appid和key填入`Yunzai-Bot\plugins\ATRI-plugin\apps\atri.js`的50和51行 （还没研究yaml文件在js里面的用法 所以直接填到源代码 我是懒狗） 正常输出应该会在控制台里输出一次日语，像这样 ![image](https://user-images.githubusercontent.com/91271243/187036380-fa56e8a6-8858-4692-ad68-4d194d3e54bf.png)
![已配置](https://user-images.githubusercontent.com/105736187/187036657-25a1501a-aa38-44e4-8698-bdd251203230.png)
已经配置了，还是不行

**Comment by qllokirin** [comment]
插件修改之后需要重启 你有重启过吗
以及建议使用notepad或者vscode编辑文件  记事本编辑有时候会出问题

**Comment by dingzhenbaohujiaran** [comment]
> 插件修改之后需要重启 你有重启过吗 以及建议使用notepad或者vscode编辑文件 记事本编辑有时候会出问题

已经多次重启了，我就是用VSCODE修改的

**Comment by qllokirin** [comment]
> > 插件修改之后需要重启 你有重启过吗 以及建议使用notepad或者vscode编辑文件 记事本编辑有时候会出问题
> 
> 已经多次重启了，我就是用VSCODE修改的

问题还是在于百度翻译这个位置  能力有限所以没有写判断语句  你方便把这个文件发给我吗，不方便的话我把我的api发给你试试也可以  加我q2456590695

**Comment by qllokirin** [comment]
报错：
```
[YzBot][23:41:23.083][INFO] recv from: [Private: 2456590695(friend)] atri说晚上
好
[YzBot][23:41:23.153][MARK] [ATRI说][atri][私聊][祈菱不是麒麟(2456590695)] atri
说晚上好
晚上好
[YzBot][23:41:23.302][ERRO] [ATRI说][atri]
[YzBot][23:41:23.302][ERRO] TypeError: Cannot read properties of undefined (read
ing '0')
    at atri (file:///C:/Users/70loKirin/Desktop/Yunzai-Bot/plugins/ATRI-plugin/a
pps/atri.js:61:37)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async PluginsLoader.deal (file:///C:/Users/70loKirin/Desktop/Yunzai-Bot/l
ib/plugins/loader.js:250:52)
```
是百度翻译api未配置好，可能是未开通通用翻译服务或未认证
`http://api.fanyi.baidu.com/product/11`点击开通
TODO:增加判断语句

**Comment by qllokirin** [comment]
> 报错：
> 
> ```
> [YzBot][23:41:23.083][INFO] recv from: [Private: 2456590695(friend)] atri说晚上
> 好
> [YzBot][23:41:23.153][MARK] [ATRI说][atri][私聊][祈菱不是麒麟(2456590695)] atri
> 说晚上好
> 晚上好
> [YzBot][23:41:23.302][ERRO] [ATRI说][atri]
> [YzBot][23:41:23.302][ERRO] TypeError: Cannot read properties of undefined (read
> ing '0')
>     at atri (file:///C:/Users/70loKirin/Desktop/Yunzai-Bot/plugins/ATRI-plugin/a
> pps/atri.js:61:37)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
>     at async PluginsLoader.deal (file:///C:/Users/70loKirin/Desktop/Yunzai-Bot/l
> ib/plugins/loader.js:250:52)
> ```
> 
> 是百度翻译api未配置好，可能是未开通通用翻译服务或未认证 `http://api.fanyi.baidu.com/product/11`点击开通 TODO:增加判断语句

目前已经更新代码，报错会有具体的提示
