### ISSUE TITLE
安装测试都正常，但使用时出现错误码54001

### ISSUE THREAD

**Issue by udcoo** [70loKirin/ATRI-plugin#8]
<img width="668" alt="image" src="https://user-images.githubusercontent.com/113132618/189189437-65eaafd0-9501-43af-8bee-3c4087e34760.png">

**Comment by qllokirin** [comment]
请检查百度翻译是否开通以及appid和key是否填写正确
![Screenshot_2022-09-09-07-47-50-76_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/91271243/189244757-775698e7-8eaf-4180-a7ca-65e415198b97.jpg)

**Comment by udcoo** [comment]
请问这样填写是否正确呢
<img width="368" alt="屏幕截图 2022-09-09 084123" src="https://user-images.githubusercontent.com/113132618/189249216-a4144ae4-8d91-41e2-8518-54c923f83b1b.png">

**Comment by udcoo** [comment]
在本地用vs编辑了，已解决
